import type { Props } from "./ShortsComposition";

export const DEMO_PROPS: Props = {
  metadata: {
    hook: "5.4 billion people are online right now.",
    body: [
      "That\u2019s 67% of every human alive today.",
      "Global internet users have grown 600% since 2000.",
      "YouTube, Facebook, and Netflix eat 80% of bandwidth.",
      "Fiber is 100\u00d7 faster than copper for the same cost.",
      "60% of web traffic now comes from mobile devices.",
      "Internet access has spread to 180+ countries.",
      "Nordic countries lead at 97% penetration.",
      "From ARPANET in 1969 to 5G in 2019.",
      "Every packet you send hops through 10 routers.",
      "Data travels as pulses of light in glass fibers.",
      "We spend our days on email, video, and search.",
      "The web was a dot \u2014 now it\u2019s the universe.",
      "Every second, 6,000 tweets and 1,000 photos are posted.",
      "1 trillion GB transferred every year.",
      "The internet never sleeps \u2014 and neither does your data.",
    ],
    cta: "Follow for more mind-blowing tech stats.",
    mood: "energetic",
    pacing: "fast",
    visualStyle: "minimal",
    title: "The Internet By Numbers",
    contentType: "educational",
    accentColor: "#4fc3f7",
    sceneDirectives: [
      { scene_template: "animated_graphic", image_motion: null, highlight_words: ["67%"],
        visual_query: null, animation_spec: { type: "counter", entry_animation: "build_in",
          duration_ms: 3000, data: { value: 67, suffix: "%", label: "of humans online" } } },
      { scene_template: "animated_graphic", image_motion: null, highlight_words: ["600%"],
        visual_query: null, animation_spec: { type: "line_chart", entry_animation: "draw",
          duration_ms: 3000, data: { points: [361, 1024, 2044, 3366, 4657, 5300],
          labels: ["2000", "2005", "2010", "2015", "2020", "2024"],
          y_label: "users (M)", highlight_drop: false } } },
      { scene_template: "animated_graphic", image_motion: null, highlight_words: ["80%"],
        visual_query: null, animation_spec: { type: "bar_chart", entry_animation: "build_in",
          duration_ms: 3000, data: { items: [{ label: "YouTube", value: 37 },
          { label: "Netflix", value: 15 }, { label: "Facebook", value: 10 },
          { label: "Other", value: 38 }], unit: "% bandwidth" } } },
      { scene_template: "animated_graphic", image_motion: null, highlight_words: ["100\u00d7"],
        visual_query: null, animation_spec: { type: "comparison_bars", entry_animation: "build_in",
          duration_ms: 3000, data: { items: [{ label: "Fiber", value: 1000 },
          { label: "Copper DSL", value: 10 }], unit: "Mbps" } } },
      { scene_template: "animated_graphic", image_motion: null, highlight_words: ["60%"],
        visual_query: null, animation_spec: { type: "percentage_fill", entry_animation: "build_in",
          duration_ms: 3000, data: { value: 60, label: "Mobile web traffic", style: "circle" } } },
      { scene_template: "animated_graphic", image_motion: null, highlight_words: ["180+"],
        visual_query: null, animation_spec: { type: "map_spread", entry_animation: "build_in",
          duration_ms: 3000, data: { highlight_countries: ["USA","GBR","DEU","FRA","JPN","BRA","IND","CHN","AUS","ZAF","RUS","CAN"],
          spread_order: true } } },
      { scene_template: "animated_graphic", image_motion: null, highlight_words: ["97%"],
        visual_query: null, animation_spec: { type: "world_highlight", entry_animation: "build_in",
          duration_ms: 3000, data: { regions: [
            { country: "NOR", intensity: 0.97 }, { country: "SWE", intensity: 0.95 },
            { country: "DNK", intensity: 0.95 }, { country: "USA", intensity: 0.90 },
            { country: "GBR", intensity: 0.93 }, { country: "IND", intensity: 0.52 },
            { country: "NGA", intensity: 0.35 }, { country: "COD", intensity: 0.20 }],
            legend: "Internet penetration" } } },
      { scene_template: "animated_graphic", image_motion: null, highlight_words: ["1969", "2019"],
        visual_query: null, animation_spec: { type: "timeline", entry_animation: "build_in",
          duration_ms: 3000, data: { events: [{ date: "1969", label: "ARPANET" },
          { date: "1983", label: "TCP/IP" }, { date: "1991", label: "World Wide Web" },
          { date: "2007", label: "iPhone" }, { date: "2019", label: "5G rollout" }],
          direction: "horizontal" } } },
      { scene_template: "animated_graphic", image_motion: null, highlight_words: ["10 routers"],
        visual_query: null, animation_spec: { type: "flow_diagram", entry_animation: "draw",
          duration_ms: 3000, data: { nodes: ["Your device","ISP","Backbone","CDN","Server"],
          style: "arrow_chain" } } },
      { scene_template: "animated_graphic", image_motion: null, highlight_words: ["light"],
        visual_query: null, animation_spec: { type: "svg_draw_path", entry_animation: "draw",
          duration_ms: 3000, data: { path: "M 0 250 Q 115 100 230 250 Q 345 400 460 250 Q 575 100 690 250 Q 805 400 920 250",
          stroke_width: 4 } } },
      { scene_template: "animated_graphic", image_motion: null,
        highlight_words: ["email", "video", "search"], visual_query: null,
        animation_spec: { type: "icon_arrangement", entry_animation: "build_in",
          duration_ms: 3000, data: { icons: ["envelope","video","magnifying-glass","chat","bell","share-network"],
          layout: "grid", labels: ["Email","Video","Search","Chat","Alerts","Share"] } } },
      { scene_template: "animated_graphic", image_motion: null, highlight_words: ["universe"],
        visual_query: null, animation_spec: { type: "shape_metaphor", entry_animation: "build_in",
          duration_ms: 3000, data: { concept: "The web expanding", style: "expanding" } } },
      { scene_template: "text_dominant", image_motion: null,
        highlight_words: ["6,000 tweets", "1,000 photos"], visual_query: null, animation_spec: null },
      { scene_template: "stat_callout", image_motion: null,
        highlight_words: ["1 trillion GB"], visual_query: null, animation_spec: null },
      { scene_template: "fullbleed", image_motion: "slow_zoom_in",
        highlight_words: ["never sleeps"],
        visual_query: "server room glowing cables fiber optic dark", animation_spec: null },
    ],
  },
  wordTimings: [],
  audioFile: "",
  durationInFrames: 1422,
  backgroundClips: [],
  bgMusicFile: "",
  _sentenceDurations: [120,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,120],
};
